version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "${MEDIA_USER_UID}:${MEDIA_USER_GID}"
    environment:
      - PUID=${MEDIA_USER_UID}
      - PGID=${MEDIA_USER_GID}
      - TZ=${TZ}
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: unless-stopped
  samba:
    image: cyrip/samba-debian:latest
    container_name: samba
    user: root
    restart: always
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./samba-entrypoint.sh:/entrypoint.sh
      - ./media:/media
      - ./samba/config:/etc/samba
      - ./samba/log:/var/log/samba
    command: >
      --username sambauser --password ${SAMBA_USER_PASS} --uid ${MEDIA_USER_UID} --gid ${MEDIA_USER_GID}
