version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "${MEDIA_USER_UID}:${MEDIA_USER_GID}"
    environment:
      - PUID=${MEDIA_USER_UID}
      - PGID=${MEDIA_USER_GID}
      - TZ=${TZ}
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: unless-stopped
